theme: jekyll-theme-slate
title: South of Scotland Enterprise
description: A corporate website
excerpt_separator: "<!--more-->"
baseurl: "/SOSE"

# The release of Jekyll Now that you're using
version: v1.2.0
plugins:
  - jekyll-relative-links

